<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="980" started-at="2014-08-05T20:16:04Z" finished-at="2014-08-05T20:16:05Z">
    <groups>
      <group name="RPNEvaluationTest1">
        <method signature="RPNEvaluationUnitTest.testEvaluateRPNNegative()[pri:0, instance:com.solutioniq.calculator.unittest.testng.RPNEvaluationUnitTest@170bea5]" name="testEvaluateRPNNegative" class="com.solutioniq.calculator.unittest.testng.RPNEvaluationUnitTest"/>
        <method signature="RPNEvaluationUnitTest.testEvaluateRPNWrongInputs()[pri:0, instance:com.solutioniq.calculator.unittest.testng.RPNEvaluationUnitTest@170bea5]" name="testEvaluateRPNWrongInputs" class="com.solutioniq.calculator.unittest.testng.RPNEvaluationUnitTest"/>
      </group> <!-- RPNEvaluationTest1 -->
      <group name="RPNEvaluationTest">
        <method signature="RPNEvaluationUnitTest.testEvaluateRPNPositive()[pri:0, instance:com.solutioniq.calculator.unittest.testng.RPNEvaluationUnitTest@170bea5]" name="testEvaluateRPNPositive" class="com.solutioniq.calculator.unittest.testng.RPNEvaluationUnitTest"/>
      </group> <!-- RPNEvaluationTest -->
    </groups>
    <test name="Default test" duration-ms="980" started-at="2014-08-05T20:16:04Z" finished-at="2014-08-05T20:16:05Z">
      <class name="com.solutioniq.calculator.unittest.testng.RPNEvaluationUnitTest">
        <test-method status="FAIL" signature="testEvaluateRPNNegative()[pri:0, instance:com.solutioniq.calculator.unittest.testng.RPNEvaluationUnitTest@170bea5]" name="testEvaluateRPNNegative" duration-ms="790" started-at="2014-08-06T01:46:04Z" finished-at="2014-08-06T01:46:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected result::-4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected result::-4
	at com.solutioniq.calculator.unittest.testng.RPNEvaluationUnitTest.testEvaluateRPNNegative(RPNEvaluationUnitTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEvaluateRPNNegative -->
        <test-method status="FAIL" signature="testEvaluateRPNPositive()[pri:0, instance:com.solutioniq.calculator.unittest.testng.RPNEvaluationUnitTest@170bea5]" name="testEvaluateRPNPositive" duration-ms="86" started-at="2014-08-06T01:46:05Z" finished-at="2014-08-06T01:46:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected result::14]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected result::14
	at com.solutioniq.calculator.unittest.testng.RPNEvaluationUnitTest.testEvaluateRPNPositive(RPNEvaluationUnitTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEvaluateRPNPositive -->
        <test-method status="FAIL" signature="testEvaluateRPNWrongInputs()[pri:0, instance:com.solutioniq.calculator.unittest.testng.RPNEvaluationUnitTest@170bea5]" name="testEvaluateRPNWrongInputs" duration-ms="49" started-at="2014-08-06T01:46:05Z" finished-at="2014-08-06T01:46:05Z">
          <exception class="com.solutioniq.calculator.core.exception.WrongExpressionException">
            <full-stacktrace>
              <![CDATA[Output String = Invalid Expression
	at com.solutioniq.calculator.service.impl.RPNEvaluator.doRPNevaluation(RPNEvaluator.java:63)
	at com.solutioniq.calculator.service.core.CalculationService.getCalculationresult(CalculationService.java:25)
	at com.solutioniq.calculator.core.businessdelegate.BusinessDelegate.doProcessing(BusinessDelegate.java:30)
	at com.solutioniq.calculator.unittest.testng.RPNEvaluationUnitTest.testEvaluateRPNWrongInputs(RPNEvaluationUnitTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- com.solutioniq.calculator.core.exception.WrongExpressionException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEvaluateRPNWrongInputs -->
      </class> <!-- com.solutioniq.calculator.unittest.testng.RPNEvaluationUnitTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
